// Builds the header menu thumbnails, public/images/menu/<id>.svg (DESIGN-SPEC section 6): each is a
// whole isometric drawing from scripts/art/menu-src/ in a tight 4:3 viewBox, with every stroke held at
// 1px at any size (vector-effect non-scaling-stroke) and white faces turned mist-50 to sit on the
// thumbnail's mist-50 panel. The header shows them as <img> (112 x 84, 88 x 66 on phones), so the
// drawings are fetched once and cached instead of being inlined into every page.
// One-off tool, not part of `npm run build`: run it after changing a source drawing or a viewBox.
//   node scripts/art/menu-thumbs.mjs
// Sources: the redesign prototype's art (D:/DevCache/claude-work/site-redesign/prototype/assets/art):
// team, documents, telemetry-off and editions match public/images; install is the step 1 drawing
// redrawn with the ML mark; answer-panel is the hero scene's panel alone; res-security is the
// redrawn security-overview drawing. The viewBoxes are the prototype's (src/partials/header.html).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, "menu-src");
const OUT = path.resolve(HERE, "../../public/images/menu");

/** id: [source file, tight 4:3 viewBox around the whole drawing] */
const THUMBS = {
  instructors: ["team.svg", "-22.1 14.7 294.2 220.6"],
  students: ["answer-panel.svg", "-55.7 -11.5 275.2 206.4"],
  learners: ["documents.svg", "-26.9 11 303.5 227.6"],
  "school-it": ["install.svg", "-24 13.3 298.9 224.2"],
  organizations: ["telemetry-off.svg", "-10.7 25.1 271.7 203.8"],
  security: ["res-security.svg", "39.9 -26.7 361.8 271.4"],
  editions: ["editions.svg", "56.9 -16 329.2 246.9"],
};
const SHAPES = /<(path|polygon|polyline|rect|circle|line|ellipse)\b([^>]*?)(\/?)>/g;

fs.mkdirSync(OUT, { recursive: true });
for (const [id, [file, vb]] of Object.entries(THUMBS)) {
  let s = fs.readFileSync(path.join(SRC, file), "utf8");
  const title = (s.match(/<title>([\s\S]*?)<\/title>/) || [, id])[1];
  s = s
    .replace(/<\?xml[^>]*>\s*/, "")
    .replace(/<!--[\s\S]*?-->\s*/g, "")
    .replace(/<title>[\s\S]*?<\/title>\s*/g, "")
    .replace(/(<svg\b[^>]*?)\sviewBox="[^"]*"/, `$1 viewBox="${vb}"`)
    .replace(/(<svg\b[^>]*?)\swidth="[\d.]+"\sheight="[\d.]+"/, "$1")
    .replace(/fill="#FFFFFF"/g, 'fill="#F8FAFC"')
    .replace(SHAPES, (_, tag, attrs, close) => {
      const a = attrs.replace(/\s(stroke-width|vector-effect)="[^"]*"/g, "");
      return `<${tag}${a} stroke-width="1" vector-effect="non-scaling-stroke"${close ? "/" : ""}>`;
    });
  if (!/viewBox="/.test(s)) throw new Error(`${file}: no viewBox`);
  const note = `<!-- Menu thumbnail (${title}). Generated by scripts/art/menu-thumbs.mjs from menu-src/${file}; do not edit. -->\n`;
  s = s.replace(/(<svg\b[^>]*>)\n?/, `$1\n${note}`);
  fs.writeFileSync(path.join(OUT, `${id}.svg`), s.endsWith("\n") ? s : s + "\n");
  console.log(`menu: ${id}.svg (${Math.round(Buffer.byteLength(s) / 102.4) / 10} KB)`);
}
